import { McpServer } from "@modelcontextprotocol/server";
import * as z from "zod/v4";
import { AdtHttpClient } from "../adt/http.js";
import { PackageApi } from "../adt/packages.js";
import { RequestApi } from "../adt/requests.js";
import { loadConnections } from "../config.js";
export function createMcpServer(initialConnections) {
    const server = new McpServer({ name: "mcp-adt", version: "0.1.0" });
    const clients = new Map();
    async function client(connection) {
        const connections = await loadConnections();
        const config = connections[connection];
        if (!config)
            throw new Error(`Unknown SAP connection '${connection}'. Available: ${Object.keys(connections).join(", ")}`);
        const fingerprint = JSON.stringify(config);
        const current = clients.get(connection);
        if (!current || current.fingerprint !== fingerprint) {
            const value = new AdtHttpClient(config);
            clients.set(connection, { fingerprint, client: value });
            return value;
        }
        return current.client;
    }
    const connectionSchema = z.object({ connection: z.string().min(1) });
    server.registerTool("package_list", {
        title: "List SAP packages",
        description: "Search SAP ABAP packages by name pattern using the ADT Repository Information System. Default pattern is Z*. Supports optional superpackage and result limit.",
        inputSchema: connectionSchema.extend({ query: z.string().optional(), superPackage: z.string().optional(), maxResults: z.number().optional() })
    }, async ({ connection, query, superPackage, maxResults }) => result(await new PackageApi(await client(connection)).list({ query, superPackage, maxResults })));
    server.registerTool("package_get", {
        title: "Get SAP package",
        description: "Read a package by name through SAP ADT.",
        inputSchema: connectionSchema.extend({ name: z.string().min(1) })
    }, async ({ connection, name }) => result(await new PackageApi(await client(connection)).get(name)));
    server.registerTool("package_create", {
        title: "Create SAP package",
        description: "Create an ABAP package (DEVC) through SAP ADT. Package names are normalized to uppercase. Local packages whose name starts with $ do not use a transport. Non-local packages require a Workbench transport request and record object changes.",
        inputSchema: connectionSchema.extend({
            name: z.string().min(1),
            description: z.string(),
            superPackage: z.string().optional(),
            responsible: z.string().optional(),
            language: z.string().optional(),
            packageType: z.enum(["development", "structure", "main"]).optional(),
            softwareComponent: z.string().optional(),
            transportLayer: z.string().optional(),
            transport: z.string().optional(),
            recordChanges: z.boolean().optional()
        })
    }, async ({ connection, ...input }) => result(await new PackageApi(await client(connection)).create(input)));
    server.registerTool("package_update", {
        title: "Update SAP package",
        description: "Update only the package description and transport layer through SAP ADT. Other package attributes are preserved.",
        inputSchema: connectionSchema.extend({ name: z.string().min(1), description: z.string(), transportLayer: z.string(), transport: z.string().optional() })
    }, async ({ connection, name, description, transportLayer, transport }) => result(await new PackageApi(await client(connection)).update(name, description, transportLayer, transport)));
    server.registerTool("package_delete", {
        title: "Delete SAP package",
        description: "Delete an ABAP package through SAP ADT. Non-local packages require a Workbench transport request.",
        inputSchema: connectionSchema.extend({ name: z.string().min(1), transport: z.string().optional() })
    }, async ({ connection, name, transport }) => result(await new PackageApi(await client(connection)).delete(name, transport)));
    server.registerTool("request_list", {
        title: "List transport requests",
        description: "List transport requests through SAP ADT.",
        inputSchema: connectionSchema
    }, async ({ connection }) => result(await new RequestApi(await client(connection)).list()));
    server.registerTool("request_get", {
        title: "Get transport request",
        description: "Read a transport request by number.",
        inputSchema: connectionSchema.extend({ number: z.string().min(1) })
    }, async ({ connection, number }) => result(await new RequestApi(await client(connection)).get(number)));
    server.registerTool("request_create", {
        title: "Create transport request",
        description: "Create a Workbench (K) or Customizing (W) transport request through SAP ADT. The request number is generated by SAP.",
        inputSchema: connectionSchema.extend({ description: z.string().min(1), category: z.enum(["K", "W"]).optional(), target: z.string().optional() })
    }, async ({ connection, ...input }) => {
        const connections = await loadConnections();
        const config = connections[connection];
        if (!config) throw new Error(`Unknown SAP connection '${connection}'.`);
        return result(await new RequestApi(await client(connection)).create({ ...input, owner: config.user }));
    });
    server.registerTool("request_update", {
        title: "Update transport request",
        description: "Update a transport request description and target through SAP ADT.",
        inputSchema: connectionSchema.extend({ number: z.string().min(1), description: z.string().min(1), target: z.string().optional() })
    }, async ({ connection, number, description, target }) => result(await new RequestApi(await client(connection)).update(number, description, target)));
    server.registerTool("request_delete", {
        title: "Delete transport request",
        description: "Delete an unreleased transport request through SAP ADT.",
        inputSchema: connectionSchema.extend({ number: z.string().min(1) })
    }, async ({ connection, number }) => result(await new RequestApi(await client(connection)).delete(number)));
    return server;
}
function result(value) {
    return { content: [{ type: "text", text: JSON.stringify(value, null, 2) }] };
}
